### ISSUE TITLE
How to stop listening?

### ISSUE THREAD

**Issue by aaronshaf** [staltz/callbag-from-event#1]
How does one trigger the `removeEventListener`? Thanks.

**Comment by staltz** [comment]
The sink should send a msg type 2 to the talkback it receives from the source (I'm on mobile)

**Comment by franciscotln** [comment]
I'm afraid you cannot stop listening using the `forEach()` sink, but you can achieve that with `subscribe(object)`, `take(number)` or `takeUntil(callbag)`.
[subscribe here](https://github.com/zebulonj/callbag-subscribe)
[take here](https://github.com/staltz/callbag-take)
[takeUntil here](https://github.com/franciscotln/callbag-take-until)

**Comment by staltz** [comment]
Yeah, it's about the sink which needs to know how to send 2 upwards.
